FROM postgres:latest

ENV POSTGRES_HOST "localhost"
ENV POSTGRES_USER "postgres"
ENV POSTGRES_PASSWORD "ER28-0652"
ENV POSTGRES_DB "gesinen"

# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
